#!/bin/bash

shopt -s expand_aliases

alias docker-compose='docker compose'

for i in "$@"; do
    if [[ "$i" = "init" ]]; then
        cp .env.example .env

        set -a
        source .env
        set +a

        docker-compose down --remove-orphans

        docker volume rm ${COMPOSE_PROJECT_NAME}-mysql

        PROJECT_NAME=${PROJECT_NAME:-hackatoniq}

        sed -i "s/^COMPOSE_PROJECT_NAME=.*/COMPOSE_PROJECT_NAME=${PROJECT_NAME}/" .env

        set -a
        source .env
        set +a

        envsubst <template.docker-compose.yaml >docker-compose.yaml

        docker volume create ${COMPOSE_PROJECT_NAME}-mysql

        docker-compose up -d --build --force-recreate --remove-orphans

        exit
    elif [[ "$i" = "up" ]]; then
        set -a
        source .env
        set +a

        envsubst <template.docker-compose.yaml >docker-compose.yaml

        docker-compose up -d --build --force-recreate --remove-orphans ${@:2}
        exit
    elif [[ "$i" = "down" ]]; then
        docker-compose down --remove-orphans ${@:2}
        exit
    elif [[ "$i" = "node" ]]; then
        docker-compose run --rm node ${@:2}
        exit
    elif [[ "$i" = "arg" ]]; then
        echo "${@:2}"
        exit
    else
        echo "Enter valid command"
        exit
    fi
done

if [[ "$@" = "" ]]; then
    echo 'Enter valid command'
fi
