#!/bin/bash

shopt -s expand_aliases

alias docker-compose='docker compose'

for i in "$@"; do
    if [[ "$i" = "init" ]]; then
        docker-compose down --remove-orphans

        docker-compose up -d --build --force-recreate --remove-orphans

        exit
    elif [[ "$i" = "up" ]]; then
        docker-compose up -d --build --force-recreate --remove-orphans ${@:2}
        exit
    elif [[ "$i" = "down" ]]; then
        docker-compose down --remove-orphans ${@:2}
        exit
    elif [[ "$i" = "node" ]]; then
        docker-compose run --rm node ${@:2}
        exit
    elif [[ "$i" = "arg" ]]; then
        echo "${@:2}"
        exit
    else
        echo "Enter valid command"
        exit
    fi
done

if [[ "$@" = "" ]]; then
    echo 'Enter valid command'
fi
