# Generated by Django 5.0.7 on 2024-08-04 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attentionCount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='todoCount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='workersRequiredCount',
        ),
        migrations.RemoveField(
            model_name='workertask',
            name='workTypeTitle',
        ),
        migrations.RemoveField(
            model_name='workertask',
            name='workersCount',
        ),
        migrations.RemoveField(
            model_name='workertask',
            name='workersRequiredCount',
        ),
        migrations.AddField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='work_type_title',
            field=models.CharField(default='Покраска стен', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='workers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='workers_required_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workertask',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workertask',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='workertask',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='workertask',
            name='work_type_title',
            field=models.CharField(default='ремонтные работы', max_length=100),
        ),
        migrations.AddField(
            model_name='workertask',
            name='workers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workertask',
            name='workers_required_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workertask',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workertask',
            name='workers',
            field=models.ManyToManyField(related_name='tasks', to='worker_shifts.worker'),
        ),
    ]
